query AnimeListQuery($perPage: Int, $page: Int, $status: MediaStatus, $format: MediaFormat, $sort: [MediaSort]) {
  Page(perPage: $perPage, page: $page) {
    pageInfo {
      currentPage
      hasNextPage
    }
    media(status: $status, format: $format, sort: $sort) {
    ...AnimeDetails
    }
  }
}

fragment AnimeDetails on Media {
    id
    isAdult
    averageScore
    siteUrl
    duration
    genres
    title {
        english
        native
    }
    description
    coverImage {
        large
        extraLarge
    }
}


